consumer:
  build: .
  command: /code/gradlew message-consumer:run -Pport=8080 -PbrokerList=kafka:9092
  links:
   - kafka
  ports:
   - "8080:8080"

zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181:2181"
kafka:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9092:9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock