consumer:
  build: .
  command: gradle clean message-consumer:run -Pport=8080 -PbrokerList=kafka:9092
  links:
   - kafka
  ports:
   - "8080:8080"

frontend:
  build: .
  command: gradle clean front-end:run -Pport=8090 -PcassandraAddress=cassandra
  links:
   - cassandra
  ports:
   - "8090:8090"

zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181:2181"

kafka:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9092:9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

nimbus:
  image: wurstmeister/storm-nimbus:0.9.3
  ports:
    - "3773:3773"
    - "3772:3772"
    - "6627:6627"
  links: 
    - zookeeper:zk
supervisor:
  image: wurstmeister/storm-supervisor:0.9.3
  ports:
    - "8000:8000"
  links: 
    - nimbus:nimbus
    - zookeeper:zk
stormui:
  image: wurstmeister/storm-ui:0.9.3
  ports:
    - "8081:8080"
  links: 
    - nimbus:nimbus
    - zookeeper:zk

cassandra:
  image: spotify/cassandra
  command: cassandra-singlenode
  ports:
    - "9160:9160"
    - "9042:9042"

